# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "docker"
    dockerswarm_sd_configs:
      - host: tcp://dockerproxy:2375
        role: nodes # Le mode permet de choisir le type d'objet decouvert entre node, task et service.
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname] # et que l'on va remplir la valeur du label "instance" avec le hostname du node docker, pour les identifier facilement!
        target_label: instance

  - job_name: "dockerswarm"
    dockerswarm_sd_configs:
      - host: tcp://dockerproxy:2375
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_name]
        target_label: __address__
        replacement: cadvisor:8080
  
  - job_name: "bananas"
    static_configs:
      - targets: ["nodeexporter:9100"]
  
  - job_name: "nasticot"
    static_configs:
      - targets: ["192.168.8.101:9100"]
  
  - job_name: "nuage"
    static_configs:
      - targets: ["192.168.8.103:9100"]
  
  - job_name: "minecraft"
    static_configs:
      - targets: ["192.168.8.101:9940"]
