{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATA_SOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Liste des dashboards",
   "type": "dashlist",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{job=\"bananas\", fstype=\"ext4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total space",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{job=\"bananas\", fstype=\"ext4\"})",
     "legendFormat": "Bananas (SD card)"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{job=\"nasticot\", fstype=\"ext4\"})",
     "legendFormat": "Nasticot (SSD)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"nasticot\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum(rate(node_cpu_seconds_total{job=\"nasticot\"}[$__rate_interval])) * 100",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"bananas\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum(rate(node_cpu_seconds_total{job=\"bananas\"}[$__rate_interval])) * 100",
     "legendFormat": "Bananas"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 7, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"nasticot\"}) by (cpu))",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"bananas\"}) by (cpu))",
     "legendFormat": "Bananas"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nasticot\"}",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"bananas\"}",
     "legendFormat": "Bananas"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"nasticot\"} - node_memory_MemAvailable_bytes{job=\"nasticot\"}) / node_memory_MemTotal_bytes{job=\"nasticot\"}",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"bananas\"} - node_memory_MemAvailable_bytes{job=\"bananas\"}) / node_memory_MemTotal_bytes{job=\"bananas\"}",
     "legendFormat": "Bananas"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"nasticot\"} - node_boot_time_seconds{job=\"nasticot\"}",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "node_time_seconds{job=\"bananas\"} - node_boot_time_seconds{job=\"bananas\"}",
     "legendFormat": "Bananas"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_filesystem_size_bytes{job=\"bananas\", device=\"/dev/root\"}) - avg(node_filesystem_avail_bytes{job=\"bananas\", device=\"/dev/root\"})) / avg(node_filesystem_size_bytes{job=\"bananas\", device=\"/dev/root\"})",
     "legendFormat": "Bananas (SD card)"
    },
    {
     "expr": "(avg(node_filesystem_size_bytes{job=\"nasticot\", fstype=\"ext4\"}) - avg(node_filesystem_avail_bytes{job=\"nasticot\", fstype=\"ext4\"})) / avg(node_filesystem_size_bytes{job=\"nasticot\", fstype=\"ext4\"})",
     "legendFormat": "Nasticot (SSD)"
    }
   ]
  },
  {
   "title": "Services docker",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_swarm_service_id=~\".+\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"nasticot\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum(rate(node_cpu_seconds_total{job=\"nasticot\"}[$__rate_interval])) * 100",
     "legendFormat": "Nasticot"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"bananas\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum(rate(node_cpu_seconds_total{job=\"bananas\"}[$__rate_interval])) * 100",
     "legendFormat": "Bananas"
    }
   ]
  }
 ]
}